DROP VIEW IF EXISTS admin_equipment_full;

CREATE TABLE equipment_models (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manufacturer_id INTEGER NOT NULL,
    name VARCHAR(128) NOT NULL,

    CONSTRAINT equipment_models_manufacturer_id_fkey
        FOREIGN KEY (manufacturer_id)
        REFERENCES manufacturers(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT equipment_models_name_not_empty
        CHECK (btrim(name) <> ''),
    CONSTRAINT uq_equipment_models_manufacturer_name
        UNIQUE (manufacturer_id, name)
);

CREATE INDEX idx_equipment_models_manufacturer_id
    ON equipment_models(manufacturer_id);

INSERT INTO manufacturers (name)
SELECT 'Не указан'
WHERE EXISTS (
    SELECT 1
    FROM equipment
    WHERE manufacturer_id IS NULL
)
ON CONFLICT (name) DO NOTHING;

UPDATE equipment
SET manufacturer_id = (
    SELECT id
    FROM manufacturers
    WHERE name = 'Не указан'
)
WHERE manufacturer_id IS NULL;

INSERT INTO equipment_models (manufacturer_id, name)
SELECT DISTINCT
    e.manufacturer_id,
    COALESCE(NULLIF(btrim(e.model), ''), 'Не указана') AS name
FROM equipment e
WHERE e.manufacturer_id IS NOT NULL
ON CONFLICT (manufacturer_id, name) DO NOTHING;

ALTER TABLE equipment
    ADD COLUMN model_id INTEGER;

UPDATE equipment e
SET model_id = em.id
FROM equipment_models em
WHERE em.manufacturer_id = e.manufacturer_id
  AND em.name = COALESCE(NULLIF(btrim(e.model), ''), 'Не указана');

ALTER TABLE equipment
    ALTER COLUMN manufacturer_id SET NOT NULL,
    ALTER COLUMN model_id SET NOT NULL;

ALTER TABLE equipment
    ADD CONSTRAINT equipment_model_id_fkey
        FOREIGN KEY (model_id)
        REFERENCES equipment_models(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;

CREATE INDEX idx_equipment_model_id
    ON equipment(model_id);

ALTER TABLE equipment
    DROP COLUMN model;

CREATE OR REPLACE VIEW admin_equipment_full AS
SELECT
    e.id,
    e.visible_id,
    e.inventory_number,
    e.serial_number,
    e.name AS equipment_name,
    e.model_id,
    em.name AS model,
    e.specifications,

    e.manufacturer_id,
    m.name AS manufacturer_name,

    e.country_id,
    c.name AS country_name,
    c.iso AS country_iso,

    e.manufacture_year,
    e.commissioning_date,
    e.issue_date,

    e.section_id,
    s.name AS section_name,

    s.workshop_id,
    w.name AS workshop_name,

    e.responsible_employee_id,
    concat_ws(
        ' ',
        emp.last_name,
        emp.first_name,
        emp.middle_name
    ) AS responsible_employee_name,
    emp.position AS responsible_employee_position,

    e.status,
    e.operation_text,
    e.notes

FROM equipment e
JOIN equipment_models em
    ON em.id = e.model_id
JOIN manufacturers m
    ON m.id = e.manufacturer_id
LEFT JOIN countries c
    ON c.id = e.country_id
JOIN sections s
    ON s.id = e.section_id
JOIN workshops w
    ON w.id = s.workshop_id
JOIN employees emp
    ON emp.id = e.responsible_employee_id;
