export type CountrySeedData = {
  iso: string;
  name: string;
};

export const countries = [
  { iso: "AD", name: "Андорра" },
  { iso: "AE", name: "ОАЭ" },
  { iso: "AF", name: "Афганистан" },
  { iso: "AG", name: "Антигуа и Барбуда" },
  { iso: "AI", name: "Ангилья" },
  { iso: "AL", name: "Албания" },
  { iso: "AM", name: "Армения" },
  { iso: "AO", name: "Ангола" },
  { iso: "AQ", name: "Антарктида" },
  { iso: "AR", name: "Аргентина" },
  { iso: "AS", name: "Американское Самоа" },
  { iso: "AT", name: "Австрия" },
  { iso: "AU", name: "Австралия" },
  { iso: "AW", name: "Аруба" },
  { iso: "AX", name: "Аландские острова" },
  { iso: "AZ", name: "Азербайджан" },
  { iso: "BA", name: "Босния и Герцеговина" },
  { iso: "BB", name: "Барбадос" },
  { iso: "BD", name: "Бангладеш" },
  { iso: "BE", name: "Бельгия" },
  { iso: "BF", name: "Буркина-Фасо" },
  { iso: "BG", name: "Болгария" },
  { iso: "BH", name: "Бахрейн" },
  { iso: "BI", name: "Бурунди" },
  { iso: "BJ", name: "Бенин" },
  { iso: "BL", name: "Сен-Бартелеми" },
  { iso: "BM", name: "Бермудские острова" },
  { iso: "BN", name: "Бруней" },
  { iso: "BO", name: "Боливия" },
  { iso: "BQ", name: "Бонэйр, Синт-Эстатиус и Саба" },
  { iso: "BR", name: "Бразилия" },
  { iso: "BS", name: "Багамы" },
  { iso: "BT", name: "Бутан" },
  { iso: "BV", name: "Остров Буве" },
  { iso: "BW", name: "Ботсвана" },
  { iso: "BY", name: "Беларусь" },
  { iso: "BZ", name: "Белиз" },
  { iso: "CA", name: "Канада" },
  { iso: "CC", name: "Кокосовые острова" },
  { iso: "CD", name: "Конго - Киншаса" },
  { iso: "CF", name: "Центрально-Африканская Республика" },
  { iso: "CG", name: "Конго - Браззавиль" },
  { iso: "CH", name: "Швейцария" },
  { iso: "CI", name: "Кот-д’Ивуар" },
  { iso: "CK", name: "Острова Кука" },
  { iso: "CL", name: "Чили" },
  { iso: "CM", name: "Камерун" },
  { iso: "CN", name: "Китай" },
  { iso: "CO", name: "Колумбия" },
  { iso: "CR", name: "Коста-Рика" },
  { iso: "CU", name: "Куба" },
  { iso: "CV", name: "Кабо-Верде" },
  { iso: "CW", name: "Кюрасао" },
  { iso: "CX", name: "Остров Рождества" },
  { iso: "CY", name: "Кипр" },
  { iso: "CZ", name: "Чехия" },
  { iso: "DE", name: "Германия" },
  { iso: "DJ", name: "Джибути" },
  { iso: "DK", name: "Дания" },
  { iso: "DM", name: "Доминика" },
  { iso: "DO", name: "Доминиканская Республика" },
  { iso: "DZ", name: "Алжир" },
  { iso: "EC", name: "Эквадор" },
  { iso: "EE", name: "Эстония" },
  { iso: "EG", name: "Египет" },
  { iso: "EH", name: "Западная Сахара" },
  { iso: "ER", name: "Эритрея" },
  { iso: "ES", name: "Испания" },
  { iso: "ET", name: "Эфиопия" },
  { iso: "FI", name: "Финляндия" },
  { iso: "FJ", name: "Фиджи" },
  { iso: "FK", name: "Фолклендские острова" },
  { iso: "FM", name: "Федеративные Штаты Микронезии" },
  { iso: "FO", name: "Фарерские острова" },
  { iso: "FR", name: "Франция" },
  { iso: "GA", name: "Габон" },
  { iso: "GB", name: "Великобритания" },
  { iso: "GD", name: "Гренада" },
  { iso: "GE", name: "Грузия" },
  { iso: "GF", name: "Французская Гвиана" },
  { iso: "GG", name: "Гернси" },
  { iso: "GH", name: "Гана" },
  { iso: "GI", name: "Гибралтар" },
  { iso: "GL", name: "Гренландия" },
  { iso: "GM", name: "Гамбия" },
  { iso: "GN", name: "Гвинея" },
  { iso: "GP", name: "Гваделупа" },
  { iso: "GQ", name: "Экваториальная Гвинея" },
  { iso: "GR", name: "Греция" },
  { iso: "GS", name: "Южная Георгия и Южные Сандвичевы острова" },
  { iso: "GT", name: "Гватемала" },
  { iso: "GU", name: "Гуам" },
  { iso: "GW", name: "Гвинея-Бисау" },
  { iso: "GY", name: "Гайана" },
  { iso: "HK", name: "Гонконг (САР)" },
  { iso: "HM", name: "Острова Херд и Макдональд" },
  { iso: "HN", name: "Гондурас" },
  { iso: "HR", name: "Хорватия" },
  { iso: "HT", name: "Гаити" },
  { iso: "HU", name: "Венгрия" },
  { iso: "ID", name: "Индонезия" },
  { iso: "IE", name: "Ирландия" },
  { iso: "IL", name: "Израиль" },
  { iso: "IM", name: "Остров Мэн" },
  { iso: "IN", name: "Индия" },
  { iso: "IO", name: "Британская территория в Индийском океане" },
  { iso: "IQ", name: "Ирак" },
  { iso: "IR", name: "Иран" },
  { iso: "IS", name: "Исландия" },
  { iso: "IT", name: "Италия" },
  { iso: "JE", name: "Джерси" },
  { iso: "JM", name: "Ямайка" },
  { iso: "JO", name: "Иордания" },
  { iso: "JP", name: "Япония" },
  { iso: "KE", name: "Кения" },
  { iso: "KG", name: "Киргизия" },
  { iso: "KH", name: "Камбоджа" },
  { iso: "KI", name: "Кирибати" },
  { iso: "KM", name: "Коморы" },
  { iso: "KN", name: "Сент-Китс и Невис" },
  { iso: "KP", name: "КНДР" },
  { iso: "KR", name: "Республика Корея" },
  { iso: "KW", name: "Кувейт" },
  { iso: "KY", name: "Острова Кайман" },
  { iso: "KZ", name: "Казахстан" },
  { iso: "LA", name: "Лаос" },
  { iso: "LB", name: "Ливан" },
  { iso: "LC", name: "Сент-Люсия" },
  { iso: "LI", name: "Лихтенштейн" },
  { iso: "LK", name: "Шри-Ланка" },
  { iso: "LR", name: "Либерия" },
  { iso: "LS", name: "Лесото" },
  { iso: "LT", name: "Литва" },
  { iso: "LU", name: "Люксембург" },
  { iso: "LV", name: "Латвия" },
  { iso: "LY", name: "Ливия" },
  { iso: "MA", name: "Марокко" },
  { iso: "MC", name: "Монако" },
  { iso: "MD", name: "Молдова" },
  { iso: "ME", name: "Черногория" },
  { iso: "MF", name: "Сен-Мартен" },
  { iso: "MG", name: "Мадагаскар" },
  { iso: "MH", name: "Маршалловы острова" },
  { iso: "MK", name: "Северная Македония" },
  { iso: "ML", name: "Мали" },
  { iso: "MM", name: "Мьянма (Бирма)" },
  { iso: "MN", name: "Монголия" },
  { iso: "MO", name: "Макао (САР)" },
  { iso: "MP", name: "Северные Марианские острова" },
  { iso: "MQ", name: "Мартиника" },
  { iso: "MR", name: "Мавритания" },
  { iso: "MS", name: "Монтсеррат" },
  { iso: "MT", name: "Мальта" },
  { iso: "MU", name: "Маврикий" },
  { iso: "MV", name: "Мальдивы" },
  { iso: "MW", name: "Малави" },
  { iso: "MX", name: "Мексика" },
  { iso: "MY", name: "Малайзия" },
  { iso: "MZ", name: "Мозамбик" },
  { iso: "NA", name: "Намибия" },
  { iso: "NC", name: "Новая Каледония" },
  { iso: "NE", name: "Нигер" },
  { iso: "NF", name: "Остров Норфолк" },
  { iso: "NG", name: "Нигерия" },
  { iso: "NI", name: "Никарагуа" },
  { iso: "NL", name: "Нидерланды" },
  { iso: "NO", name: "Норвегия" },
  { iso: "NP", name: "Непал" },
  { iso: "NR", name: "Науру" },
  { iso: "NU", name: "Ниуэ" },
  { iso: "NZ", name: "Новая Зеландия" },
  { iso: "OM", name: "Оман" },
  { iso: "PA", name: "Панама" },
  { iso: "PE", name: "Перу" },
  { iso: "PF", name: "Французская Полинезия" },
  { iso: "PG", name: "Папуа — Новая Гвинея" },
  { iso: "PH", name: "Филиппины" },
  { iso: "PK", name: "Пакистан" },
  { iso: "PL", name: "Польша" },
  { iso: "PM", name: "Сен-Пьер и Микелон" },
  { iso: "PN", name: "Острова Питкэрн" },
  { iso: "PR", name: "Пуэрто-Рико" },
  { iso: "PS", name: "Палестинские территории" },
  { iso: "PT", name: "Португалия" },
  { iso: "PW", name: "Палау" },
  { iso: "PY", name: "Парагвай" },
  { iso: "QA", name: "Катар" },
  { iso: "RE", name: "Реюньон" },
  { iso: "RO", name: "Румыния" },
  { iso: "RS", name: "Сербия" },
  { iso: "RU", name: "Россия" },
  { iso: "RW", name: "Руанда" },
  { iso: "SA", name: "Саудовская Аравия" },
  { iso: "SB", name: "Соломоновы острова" },
  { iso: "SC", name: "Сейшельские острова" },
  { iso: "SD", name: "Судан" },
  { iso: "SE", name: "Швеция" },
  { iso: "SG", name: "Сингапур" },
  { iso: "SH", name: "Остров Святой Елены" },
  { iso: "SI", name: "Словения" },
  { iso: "SJ", name: "Шпицберген и Ян-Майен" },
  { iso: "SK", name: "Словакия" },
  { iso: "SL", name: "Сьерра-Леоне" },
  { iso: "SM", name: "Сан-Марино" },
  { iso: "SN", name: "Сенегал" },
  { iso: "SO", name: "Сомали" },
  { iso: "SR", name: "Суринам" },
  { iso: "SS", name: "Южный Судан" },
  { iso: "ST", name: "Сан-Томе и Принсипи" },
  { iso: "SV", name: "Сальвадор" },
  { iso: "SX", name: "Синт-Мартен" },
  { iso: "SY", name: "Сирия" },
  { iso: "SZ", name: "Эсватини" },
  { iso: "TC", name: "Тёркс и Кайкос" },
  { iso: "TD", name: "Чад" },
  { iso: "TF", name: "Французские Южные территории" },
  { iso: "TG", name: "Того" },
  { iso: "TH", name: "Таиланд" },
  { iso: "TJ", name: "Таджикистан" },
  { iso: "TK", name: "Токелау" },
  { iso: "TL", name: "Восточный Тимор" },
  { iso: "TM", name: "Туркменистан" },
  { iso: "TN", name: "Тунис" },
  { iso: "TO", name: "Тонга" },
  { iso: "TR", name: "Турция" },
  { iso: "TT", name: "Тринидад и Тобаго" },
  { iso: "TV", name: "Тувалу" },
  { iso: "TW", name: "Тайвань" },
  { iso: "TZ", name: "Танзания" },
  { iso: "UA", name: "Украина" },
  { iso: "UG", name: "Уганда" },
  { iso: "UM", name: "Внешние малые острова (США)" },
  { iso: "US", name: "Соединенные Штаты" },
  { iso: "UY", name: "Уругвай" },
  { iso: "UZ", name: "Узбекистан" },
  { iso: "VA", name: "Ватикан" },
  { iso: "VC", name: "Сент-Винсент и Гренадины" },
  { iso: "VE", name: "Венесуэла" },
  { iso: "VG", name: "Виргинские острова (Великобритания)" },
  { iso: "VI", name: "Виргинские острова (США)" },
  { iso: "VN", name: "Вьетнам" },
  { iso: "VU", name: "Вануату" },
  { iso: "WF", name: "Уоллис и Футуна" },
  { iso: "WS", name: "Самоа" },
  { iso: "YE", name: "Йемен" },
  { iso: "YT", name: "Майотта" },
  { iso: "ZA", name: "Южно-Африканская Республика" },
  { iso: "ZM", name: "Замбия" },
  { iso: "ZW", name: "Зимбабве" },
] as const satisfies readonly CountrySeedData[];