-- ============================================================
-- DB-level identity numbering helpers
-- ============================================================
-- These functions keep autogenerated integer IDs safe even when
-- an ID is manually inserted through the application or pgAdmin.

CREATE OR REPLACE FUNCTION app_sync_identity_sequence(
    p_table  REGCLASS,
    p_column TEXT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_sequence_name TEXT;
    v_max_id        BIGINT;
    v_has_rows      BOOLEAN;
BEGIN
    v_sequence_name := pg_get_serial_sequence(p_table::TEXT, p_column);

    IF v_sequence_name IS NULL THEN
        RAISE EXCEPTION 'No serial/identity sequence found for %.%', p_table, p_column;
    END IF;

    EXECUTE format(
        'SELECT COALESCE(MAX(%1$I), 1), EXISTS (SELECT 1 FROM %2$s)',
        p_column,
        p_table
    )
    INTO v_max_id, v_has_rows;

    PERFORM setval(v_sequence_name, v_max_id, v_has_rows);

    IF v_has_rows THEN
        RETURN v_max_id + 1;
    END IF;

    RETURN 1;
END;
$$;

COMMENT ON FUNCTION app_sync_identity_sequence(REGCLASS, TEXT)
IS 'Synchronizes an identity/serial sequence with MAX(id) and returns the next safe value';


CREATE OR REPLACE FUNCTION app_next_identity_id(
    p_table  REGCLASS,
    p_column TEXT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN app_sync_identity_sequence(p_table, p_column);
END;
$$;

COMMENT ON FUNCTION app_next_identity_id(REGCLASS, TEXT)
IS 'Returns the next safe identity value for display in application forms';


CREATE OR REPLACE FUNCTION app_sync_identity_after_insert()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_table REGCLASS;
    v_column TEXT;
BEGIN
    v_column := COALESCE(TG_ARGV[0], 'id');
    v_table := format('%I.%I', TG_TABLE_SCHEMA, TG_TABLE_NAME)::REGCLASS;

    PERFORM app_sync_identity_sequence(v_table, v_column);

    RETURN NULL;
END;
$$;

COMMENT ON FUNCTION app_sync_identity_after_insert()
IS 'Statement-level trigger helper that keeps identity sequence aligned after manual ID inserts';


DROP TRIGGER IF EXISTS trg_equipment_sync_identity_after_insert ON equipment;

CREATE TRIGGER trg_equipment_sync_identity_after_insert
AFTER INSERT ON equipment
FOR EACH STATEMENT
EXECUTE FUNCTION app_sync_identity_after_insert('id');
